// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWatchedDomain(arg1:string,arg2:string):Promise<main.QueryResult>;

export function BatchCheckCertificates(arg1:string):Promise<main.BatchQueryResult>;

export function CheckCertificate(arg1:string):Promise<main.QueryResult>;

export function CheckNotifications():Promise<main.NotificationResult>;

export function ClearHistory():Promise<void>;

export function DisableManualMode(arg1:number):Promise<void>;

export function GetHistory(arg1:number):Promise<main.HistoryQueryResult>;

export function GetWatchedDomains():Promise<main.WatchedDomainsResult>;

export function ImportDomainsFromText(arg1:string):Promise<main.ImportDomainsResult>;

export function RefreshAllWatchedDomains():Promise<main.WatchedDomainsResult>;

export function RefreshWatchedDomain(arg1:string):Promise<main.QueryResult>;

export function RemoveWatchedDomain(arg1:number):Promise<void>;

export function UpdateManualCertInfo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateNotifySettings(arg1:number,arg2:boolean,arg3:number):Promise<void>;

export function UpdateWatchedDomainNickname(arg1:number,arg2:string):Promise<void>;
