// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchedDomain(arg1, arg2) {
  return window['go']['main']['App']['AddWatchedDomain'](arg1, arg2);
}

export function BatchCheckCertificates(arg1) {
  return window['go']['main']['App']['BatchCheckCertificates'](arg1);
}

export function CheckCertificate(arg1) {
  return window['go']['main']['App']['CheckCertificate'](arg1);
}

export function CheckNotifications() {
  return window['go']['main']['App']['CheckNotifications']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DisableManualMode(arg1) {
  return window['go']['main']['App']['DisableManualMode'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetWatchedDomains() {
  return window['go']['main']['App']['GetWatchedDomains']();
}

export function ImportDomainsFromText(arg1) {
  return window['go']['main']['App']['ImportDomainsFromText'](arg1);
}

export function RefreshAllWatchedDomains() {
  return window['go']['main']['App']['RefreshAllWatchedDomains']();
}

export function RefreshWatchedDomain(arg1) {
  return window['go']['main']['App']['RefreshWatchedDomain'](arg1);
}

export function RemoveWatchedDomain(arg1) {
  return window['go']['main']['App']['RemoveWatchedDomain'](arg1);
}

export function UpdateManualCertInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateManualCertInfo'](arg1, arg2, arg3);
}

export function UpdateNotifySettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNotifySettings'](arg1, arg2, arg3);
}

export function UpdateWatchedDomainNickname(arg1, arg2) {
  return window['go']['main']['App']['UpdateWatchedDomainNickname'](arg1, arg2);
}
